CREATE DATABASE shiro;
USE shiro;

CREATE TABLE user (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50),
    password VARCHAR(50),
    salt VARCHAR(50),
    role VARCHAR(50)
) CHARSET = UTF8 ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE role(
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    role VARCHAR(50),
    description VARCHAR(50)
) CHARSET = UTF8 ENGINE = InnoDB AUTO_INCREMENT = 1000;

CREATE TABLE permission(
	id	BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    permission VARCHAR(50),
    description VARCHAR(50)
) CHARSET = UTF8 ENGINE = InnoDB AUTO_INCREMENT = 2000;

CREATE TABLE user_role(
    userID BIGINT,
    roleID BIGINT
) CHARSET = UTF8 ENGINE = InnoDB;

CREATE TABLE role_permission(
    roleID BIGINT(20),
    permissionID BIGINT(20)
) CHARSET = UTF8 ENGINE = InnoDB;